// <auto-generated />
using System;
using FamilyArchiveBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyArchiveBackend.Migrations
{
    [DbContext(typeof(FamilyArchiveContext))]
    partial class FamilyArchiveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyArchiveBackend.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaidenName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.MemberRelationship", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("MemberRelationships");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.MemberSpouse", b =>
                {
                    b.Property<int>("Spouse1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Spouse2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DivorcedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MarriedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Spouse1Id", "Spouse2Id");

                    b.HasIndex("Spouse2Id");

                    b.ToTable("MemberSpouses");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.Member", b =>
                {
                    b.HasOne("FamilyArchiveBackend.Models.User", "Owner")
                        .WithMany("Members")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.MemberRelationship", b =>
                {
                    b.HasOne("FamilyArchiveBackend.Models.Member", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyArchiveBackend.Models.Member", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.MemberSpouse", b =>
                {
                    b.HasOne("FamilyArchiveBackend.Models.Member", "Spouse1")
                        .WithMany("Spouses1")
                        .HasForeignKey("Spouse1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyArchiveBackend.Models.Member", "Spouse2")
                        .WithMany("Spouses2")
                        .HasForeignKey("Spouse2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Spouse1");

                    b.Navigation("Spouse2");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.Member", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");

                    b.Navigation("Spouses1");

                    b.Navigation("Spouses2");
                });

            modelBuilder.Entity("FamilyArchiveBackend.Models.User", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
